# =============================================================================
# File Documentation (auto-inserted)
# Generated: 2025-09-26T23:01:52
# Path: collections/requirements.yml
# Purpose: TBD
# Notes: This header was added automatically based on the comment schema.
# =============================================================================

collections:
  # -----------------------------------------------------------------------------
  # Task: community.general
  # Description: TBD
  # When: n/a
  # Tags: n/a
  # Changed by: auto-commenter
  # -----------------------------------------------------------------------------
  - name: community.general
