



- block:
    - name: assert required vars for update_system tasks
      ansible.builtin.assert:
        that:
          - cachetime is defined
          - autoremove is defined
          - autoclean is defined
          - quiet is defined
        fail_msg: >-
          Missing mandatory variables for update_system: {{
            (
              (['cachetime'] if (cachetime is not defined) else []) +
              (['autoremove'] if (autoremove is not defined) else []) +
              (['autoclean'] if (autoclean is not defined) else []) +
              (['quiet'] if (quiet is not defined) else [])
            ) | join(', ')
          }}.
        success_msg: "update_system: all mandatory vars ok"
        quiet: "{{ quiet }}"

    - name: upgrading Cache (Cache lifetime {{ cachetime }}s)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: "{{ cachetime }}"

    - name: Upgrade Packages
      ansible.builtin.apt:
        upgrade: yes
        autoremove: "{{ autoremove }}"
        autoclean: "{{ autoclean }}"

  vars:
    defaults: "{{ lookup('file', tasks_dir ~ '/update_system/defaults/main.yml') | from_yaml }}"
    cachetime: "{{ cache_valid_time | default(defaults.cache_valid_time) | int }}"
    autoremove: "{{ auto_remove | default(defaults.auto_remove) | bool }}"
    autoclean: "{{ auto_clean | default(defaults.auto_clean) | bool }}"
    quiet: "{{ task_quiet | default(defaults.task_quiet) | bool }}"

  environment:
    DEBIAN_FRONTEND: noninteractive
