- name: assert hostname var is set
  ansible.builtin.assert:
      that:
        - hostname is defined
        - (hostname | trim | length) > 0
      fail_msg: "BREAK: var 'hostname' is not defined or empty."
      success_msg: "hostname={{ hostname }} asseration passed"

- name: gahter network facts
  ansible.builtin.setup:
    gather_subset: [network]

- name: Check if short name is identical (hostname can be FQDN)
  ansible.builtin.assert:
    that:
      - (hostname | default('') | trim | length) > 0
      - ((hostname | trim | lower).split('.')[0]) == (ansible_facts.hostname | lower)
    fail_msg: "Mismatch: runtime short='{{ ansible_facts.hostname }}', provided='{{ hostname }}'"
    success_msg: hostname match! success