# =============================================================================
# File Documentation (auto-inserted)
# Generated: 2025-09-26T23:01:52
# Path: roles/php/vars/main.yml
# Purpose: TBD
# Notes: This header was added automatically based on the comment schema.
# =============================================================================

self_role: php
php_apt_packages:
  - libapache2-mod-php
  - php-imagick
  - php-common
  - php-curl
  - php-gd 
  - php-gmp 
  - php-bcmath
  - php-imap
  - php-intl 
  - php-json 
  - php-mbstring 
  - php-mysql 
  - php-ssh2 
  - php-xml
  - php-zip 
  - php-apcu 
  - php-redis 
  - php-ldap 
  - php-phpseclib
enable_reboot: true
