


- block:
  - name: Check if reboot is necessary
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_flag
    when: enabled
  - name: Reboot (if necessary)
    ansible.builtin.reboot:
      msg: "Reboot after kernel/lib upgrade"
      reboot_timeout: timeout
    when: reboot_flag.stat.exists and enabled
  - name: Reboot (force)
    ansible.builtin.reboot:
      msg: "force reboot"
      reboot_timeout: timeout
    when: not reboot_flag.stat.exists and enabled and force

  vars:
    defaults: "{{ lookup('file', tasks_dir ~ '/reboot/defaults/main.yml') | from_yaml }}"
    enabled: "{{ enable_reboot | default(defaults.enable_reboot) | bool }}"
    force: "{{ force_reboot | default(defaults.force_reboot) | bool }}"
    timeout: "{{ reboot_timeout | default(defaults.reboot_timeout) | bool }}"
