# =============================================================================
# File Documentation (auto-inserted)
# Generated: 2025-09-26T23:01:52
# Path: tasks/reboot/ubuntu/all/main.yml
# Purpose: TBD
# Notes: This header was added automatically based on the comment schema.
# =============================================================================

- block:
  # -----------------------------------------------------------------------------
  # Task: Check if reboot is necessary
  # Description: TBD
  # When: enabled
  # Tags: n/a
  # Changed by: auto-commenter
  # -----------------------------------------------------------------------------
  - name: Check if reboot is necessary
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_flag
    when: enabled
  # -----------------------------------------------------------------------------
  # Task: Reboot (if necessary)
  # Description: TBD
  # When: reboot_flag.stat.exists and enabled
  # Tags: n/a
  # Changed by: auto-commenter
  # -----------------------------------------------------------------------------
  - name: Reboot (if necessary)
    ansible.builtin.reboot:
      msg: "Reboot after kernel/lib upgrade"
      reboot_timeout: timeout
    when: reboot_flag.stat.exists and enabled
  # -----------------------------------------------------------------------------
  # Task: Reboot (force)
  # Description: TBD
  # When: not reboot_flag.stat.exists and enabled and force
  # Tags: n/a
  # Changed by: auto-commenter
  # -----------------------------------------------------------------------------
  - name: Reboot (force)
    ansible.builtin.reboot:
      msg: "force reboot"
      reboot_timeout: timeout
    when: not reboot_flag.stat.exists and enabled and force

  vars:
    defaults: "{{ lookup('file', tasks_dir ~ '/reboot/defaults/main.yml') | from_yaml }}"
    enabled: "{{ enable_reboot | default(defaults.enable_reboot) | bool }}"
    force: "{{ force_reboot | default(defaults.force_reboot) | bool }}"
    timeout: "{{ reboot_timeout | default(defaults.reboot_timeout) | bool }}"