- name: install required ufw packages
  include_tasks: "{{ tasks_dir }}/install_packages/{{ os_dir }}/main.yml"
  vars:
    packages: "{{ ufw_apt_packages }}"
    reboot_enabled: "{{ upgrade_reboot }}"