# =============================================================================
# File Documentation (auto-inserted)
# Generated: 2025-09-27T20:59:59Z
# Modified: 2025-09-27T20:59:59Z
# Path: tasks/reboot/defaults/main.yml
# Purpose: Updated to schema v1
# Notes: -
# =============================================================================

# =============================================================================
# File Summary (auto-inserted)
# Overview:
#   Role        : {{ summary.role | default(derived.role | default('n/a')) }}
#   Purpose     : {{ summary.purpose | default(meta.purpose | default('TBD')) }}
#   OS Scope    : {{ summary.os | default(derived.os | default('generic')) }} ({{ summary.os_scope | default(derived.os_scope | default('all')) }})
# Counts:
#   Tasks       : {{ summary.tasks_total | default('?') }}
#   Includes    : {{ summary.includes_total | default('?') }}
#   Handlers    : {{ summary.handlers_total | default('?') }}
#   Imports     : {{ summary.imports_total | default('?') }}
# Sets:
#   Modules     : {{ (summary.modules | default([])) | join(', ') | default('none') }}
#   Tags        : {{ (summary.tags | default([])) | join(', ') | default('none') }}
#   Guards      : {{ (summary.guards | default([])) | join(', ') | default('none') }}
# Flags:
#   Become      : {{ summary.become | default(derived.become | default('false')) }}
#   Idempotency : {{ summary.idempotency | default('convergent/guarded') }}
# Risk:
#   Level       : {{ summary.risk | default('medium') }}
#   Downtime    : {{ summary.downtime | default('n/a') }}
# Description: {{ summary.description | default('TBD') }}
# =============================================================================

# =============================================================================
# File Narrative (auto-inserted)
# This task file orchestrates a controlled, guarded operation on {{ summary.os | default(derived.os | default('generic')) }} ({{ summary.os_scope | default(derived.os_scope | default('all')) }}) hosts. When the guard condition{{ 's' if (summary.guards | default([]) | length) > 1 else '' }} {{ (summary.guards | default([])) | join(' and ') | default('is met') }} holds, it executes the main action using {{ (summary.modules | default([])) | join(', ') | default('the appropriate modules') }}. It then verifies availability, records minimal diagnostics, and exposes concise facts for downstream logic. The procedure is designed to be idempotent and convergent; reruns should result in no changes once the desired state is reached. Operationally, this action may be disruptive and typically requires privilege escalation; plan for a short, bounded downtime {{ '(' ~ summary.downtime ~ ')' if summary.downtime is defined else '' }}.
# =============================================================================

enabled_reboot: true
force_reboot: false
