- name: Ensure IPv6 mode in /etc/default/ufw
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/ufw
    regexp: '^IPV6='
    line: "IPV6={{ ufw_ipv6 | ternary('yes','no') }}"
    backup: true
  notify: Reload UFW

- name: Set default incoming policy
  become: true
  community.general.ufw:
    direction: incoming
    policy: "{{ ufw_default_incoming }}"

- name: Set default outgoing policy
  become: true
  community.general.ufw:
    direction: outgoing
    policy: "{{ ufw_default_outgoing }}"

- name: Set default routed policy
  become: true
  community.general.ufw:
    direction: routed
    policy: "{{ ufw_default_routed }}"

- name: Set logging level
  become: true
  community.general.ufw:
    logging: "{{ ufw_logging }}"