- name: base_test
  hosts: owncloud
  gather_facts: true
  remote_user: root
  tasks:
    - name: debug
      debug:
        var: ansible_facts
    #- name: set domain as hostname
    #  include_tasks: "{{ self_tasks_dir }}/users.yml"
    #  vars:
    #    user_name: "{{ item }}"
        