- name: base_test
  hosts: owncloud
  gather_facts: true
  remote_user: root
  tasks:
    - name: debug
      debug:
        var: os_dir
    
    - name: set domain as hostname
      include_tasks: "{{ tasks_dir }}/set_hostname/{{ os_dir }}/main.yml"
      vars:
        hostname: "{{ domain }}"

  vars:
    domain: "testcloud.leikam-barz.de"
        