- name: base_test
  hosts: owncloud
  gather_facts: true
  remote_user: root
  tasks:
    - name: debug
      debug:
        var: os_dir
  roles:
    - php

    #- name: set domain as hostname
    #  include_tasks: "{{ tasks_dir }}/set_hostname/{{ os_dir }}/main.yml"
    #  vars:
    #    hostname: "{{ domain }}"

    #- name: update system
    #  include_tasks: "{{ tasks_dir }}/update_system/{{ os_dir }}/main.yml"
    #  vars:
    #    reboot_enabled: "{{ upgrade_reboot }}"

  vars:
    domain: "testcloud.leikam-barz.de"
    check_hostname: true
    upgrade_reboot: true