- name: base_test
  hosts: owncloud
  gather_facts: true
  remote_user: root
  pre_tasks:
    - name: load host deployment congfig for host "{{ inventory_hostname }}"
      ansible.builtin.include_vars:
        file: "{{ vars_dir }}/hosts/{{ inventory_hostname }}.yml"
        name: host_cfg  
  tasks:
    - name: debug
      debug:
        var: host_cfg
  roles: host_cfg.deployment.roles
  #roles:
  #  - ufw
  #  - php

    #- name: set domain as hostname
    #  include_tasks: "{{ tasks_dir }}/set_hostname/{{ os_dir }}/main.yml"
    #  vars:
    #    hostname: "{{ domain }}"

    #- name: update system
    #  include_tasks: "{{ tasks_dir }}/update_system/{{ os_dir }}/main.yml"
    #  vars:
    #    reboot_enabled: "{{ upgrade_reboot }}"

  vars:
    domain: "testcloud.leikam-barz.de"
    check_hostname: true
    upgrade_reboot: true