- name: base_test
  hosts: owncloud
  gather_facts: true
  remote_user: root
  tasks:
    - name: debug
      debug:
        var: os_dir
    
    - name: set domain as hostname
      include_tasks: "{{ tasks_dir }}/set_hostname/{{ os_dir }}/main.yml"
      vars:
        hostname: "{{ domain }}"

    - name: Nur Netzwerk-Facts sammeln (liefert fqdn/hostname)
      ansible.builtin.setup:
        gather_subset: [network]

    - name: debug
      debug:
        var: ansible_facts.hostname
    

  vars:
    domain: "testcloud.leikam-barz.de"
        