- name: update repo
  hosts: localhost
  gather_facts: false

  tasks:
    - name: updating local ansible git repo
      ansible.builtin.include_tasks: 
        file: "{{ tasks_dir }}/git_pull_repo/{{ os_dir }}/main.yml"