# =============================================================================
# File Documentation (auto-inserted)
# Generated: 2025-09-26T23:01:52
# Path: tasks/set_hostname/ubuntu/all/main.yml
# Purpose: TBD
# Notes: This header was added automatically based on the comment schema.
# =============================================================================

# -----------------------------------------------------------------------------

# Task: set hostname var

# Description: TBD

# When: (

# Tags: n/a

# Changed by: auto-commenter

# -----------------------------------------------------------------------------

- name: set hostname var
  ansible.builtin.set_fact:
    new_hostname: "{{ host_cfg.hostname | default('unnamed', true) }}"

# -----------------------------------------------------------------------------

# Task: Set hostname

# Description: TBD

# When: (

# Tags: n/a

# Changed by: auto-commenter

# -----------------------------------------------------------------------------

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ new_hostname }}"

# -----------------------------------------------------------------------------

# Task: Check Hostname

# Description: TBD

# When: (

# Tags: n/a

# Changed by: auto-commenter

# -----------------------------------------------------------------------------

- name: Check Hostname
  include_tasks: "{{ tasks_dir }}/check_hostname/{{ os_dir }}/main.yml"
  vars:
    hostname: "{{ new_hostname }}"
  when: (
        (host_cfg.options.enable_hostname_check | default(false)) or
        (enable_hostname_check | default(false))
      ) | bool
