- name: verify task exists
  ansible.builtin.stat:
    path: "{{ tasks_dir }}/{{ task_name }}/{{ os_dir }}/main.yml"
  register: local_art
  delegate_to: localhost
  vars:
    ansible_connection: local

#- name: debug
#  ansible.builtin.debug:
#    var: local_art

- name: run task "{{ task_name }}" 
  ansible.builtin.include_tasks: 
    file: "{{ local_art.stat.path }}"
  when: local_art.stat.exists | default(false) | bool